### PR TITLE
Updated composer.json

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Comment by adojck** [comment]
Hello, I have a question on `"type"` in `composer.json`

Why was it changed from `"contao-bundle"` to `"symfony-bundle"`? Which is the correct type to use?

In documentation it says it should be `"contao-bundle"`: https://docs.contao.org/dev/guides/first-bundle/

Could you please clarify what is the difference between these two types? What effect does it have?

**Comment by fritzmg** [comment]
Yeah this change seems wrong to me. @aschempp any particular reason for that?

**Comment by aschempp** [comment]
Well yes... i think we changed it because the package should not be visible on the package indexer. But Imm not sure why it is on packagist at all 🤷‍♂️

**Comment by adojck** [comment]
I use this skeleton-bundle as a basis for my Contao extension. In my case it should be type `"contao-bundle"`?

**Comment by fritzmg** [comment]
@aschempp I see. But since this package is supposed to be a pointer on how to create a contao bundle, it should remain `contao-bundle`. Just remove it from packagist, I guess? :)

@adojck yes, it should be `contao-bundle`.

**Comment by leofeyer** [comment]
The package is not (or no longer) on packagist.org, therefore we should revert the package type change (see #6).

**Pull request merged**
